# Generated by Django 5.2.5 on 2025-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
